name: Jupiter Project Pipeline

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  TERRAFORM_ACTION: apply
  GITHUB_USERNAME: kncloudproject
  REPOSITORY_NAME: application-codes
  WEB_FILE_ZIP: rentzone.zip
  WEB_FILE_UNZIP: rentzone
  FLYWAY_VERSION: 9.8.1

jobs:
  wait_for_approval:
    name: Manual Approval Required
    runs-on: ubuntu-latest
    environment:
      name: approval-gate  # requires manual approval
    steps:
      - name: Awaiting Manual Approval
        run: echo "Waiting for approval from kncloudproject."

